import { HomePageComponent } from "@/PageComponent/Home";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          KR Institute | #1 HealthCare Training Provider in Singapore{" "}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomePageComponent />
    </>
  );
}
